const data = {
  hot: [
    { height: 233,imgFlag:true, title: "Thai food is so good🤤", description: "Siam Station | Irvine, CA \nThai food is so good🤤here are the #deats : \n-Pad Thai \n -Pad See Ew \n-Chinese Broccoli", 
      img: "/Post1/Post.jpg", accountName: "clovchoi", accountPic: "/Post1/Account.png",
      likesNum: 520, commentNum: 5, collectionNum: 1, restaurantName:"Siam Station",
      reviewRank:4.3, reviewNum: 128, followingFlag: false, feature: "Hot"},

    { height: 272, imgFlag:false, title: "Had to get some vids of my first time at @iniristorante!", description: "It’s been on my list of places to try for months 🤤 been feeling inspired to create food content outside of the kitchen again so I thought I’d share! (Bringing back the Yelp elite in me hahaha)🫶🏼", 
      img: "/Post2/Post.mp4", accountName: "skatewithlinda", accountPic: "/Post2/Account.png",
      likesNum: 165, commentNum: 32, collectionNum: 76, restaurantName:"Ini Ristorane",
      reviewRank:4.5, reviewNum: 231, followingFlag: true, feature: "Hot"},

    { height: 185, imgFlag:true, title: "I have a good review for you all today 🫶", description: "hello friends! \nI have a good review for you all today 🫶\nSo my family and I went to @folksrestaurantand we knew this place was amazing, but it really blew our minds \n", 
      img: "/Post3/Post.jpg", accountName: "bishesdishes_", accountPic: "/Post3/Account.png",
      likesNum: 326, commentNum: 5, collectionNum: 0, restaurantName:"Folks Pizzeria",
      reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},

    { height: 270, imgFlag:true, title: "Introducing Northern-style Vietnamese cuisine", description: "\nCLICK HERE TO FOLLOW\n@supnoodlebar \n\nIf you would like to have your restaurant featured on our site for FREE, please email us at\naapiownedrestaurants@gmail.com", 
      img: "/Post4/Post.jpg", accountName: "fkndeliciousness", accountPic: "/Post4/Account.png",
      likesNum: 772, commentNum: 29, collectionNum: 0, restaurantName:"SÚP NOODLE BAR",
      reviewRank:4.5, reviewNum: 704, followingFlag: false, feature: "Hot"},

    { height: 275, imgFlag:false, title: "Anyone else obsessed with bone marrow? 😅", description: "anyone else obsessed with bone marrow? 😅\n\nft. @nep.cafe\n\n#bonemarrow #bonemarrowpasta #banhmichao #bánhmìchảo #thitnuong", 
      img: "/Post5/Post.mp4", accountName: "takeoneforroad", accountPic: "/Post5/account.png",
      likesNum: 1322, commentNum: 981, collectionNum: 2312, restaurantName:"Nép cafe & brunch",
      reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},

    { height: 260, imgFlag:true, title: "everything we ate at @anjin_costamesa", description: "everything we ate at @anjin_costamesa", 
      img: "/Post6/Post.jpg", accountName: "johnson.doan", accountPic: "/Post6/account.png",
      likesNum: 3965, commentNum: 966, collectionNum: 1255, restaurantName:"Anjin",
      reviewRank:4.6, reviewNum: 486, followingFlag: true, feature: "Hot"},

    { height: 198, imgFlag:true, title: "📌 Rising Phoenix Milk Tea $5.00 USD", description: "Best Oolong milk tea I’ve ever had! Their boba milk tea was truly exceptional, you could literally taste the quality of the tea compared to many other boba chains! The service was 10/10, they wanted me to have a taste of my drink first before leaving to make sure I got my desired amount of sweetness (1-5). 10/10 recommended;)", 
      img: "/Post7/Post.jpg", accountName: "foodie.914", accountPic: "/Post7/account.png",
      likesNum: 754, commentNum: 28, collectionNum: 76, restaurantName:"Orobae",
      reviewRank:4.6, reviewNum: 384, followingFlag: false, feature: "Hot"},

    { height: 280, imgFlag:true, title: "Very cute spot next to the beach", description: "", 
    img: "/Post8/Post.jpg", accountName: "Cindy_0314", accountPic: "/Post8/account.png",
    likesNum: 36597, commentNum: 3223, collectionNum: 2756, restaurantName:"Larsen",
    reviewRank:3.8, reviewNum: 132, followingFlag: true, feature: "Hot"},

    { height: 214, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post9.mp4", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 176, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},
    { height: 122, imgFlag:true, title: "Very cute spot next to the beach", description: "", 
    img: "/Post10.jpg", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 187, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "Hot"},
    { height: 298, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post3.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 178, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "Hot"},
    { height: 300, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post4.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 169, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},
    { height: 180, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post1.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 196, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},
    { height: 270, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post2.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 153, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "Hot"},
    { height: 180, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post3.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 163, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},
    { height: 269, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post4.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 179, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot"},
//   ],
//   "Following":[
    { height: 283, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post1.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 2199, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "Following"},
    { height: 283, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post4.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 2199, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "Following"},
    { height: 202, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post1.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 165, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Following"},
    { height: 255, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post2.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 1388, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Following"},
//   ],
//   "New":[
    { height: 190, imgFlag:false, title: "jk jhbgvcd ", description: "", 
    img: "/Post2.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 129, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "New"},
    { height: 260, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post3.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 1139, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "New"},
    { height: 110, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post1.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 197, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "New"},
    { height: 221, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post4.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 119, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "New"},
//   ],
//   "Best":[
    { height: 283, imgFlag:false, title: "Very cute spot next to the beach", description: "", 
    img: "/Post1.png", accountName: "Cindy_0314", accountPic: "/testAccountPic.png", likesNum: 2199, commentNum: 32, collectionNum: 76, restaurantName:"Resttttaurant", reviewRank:4.7, reviewNum: 80, followingFlag: false, feature: "Best"},
  ],
};

export default data;
