const data = {
  hot: [

// Hot Reviews
    { height: 233, imgFlag: false, 
        title: "A Delightful Thai Adventure",
        description: "The Thai restaurant in town is absolutely amazing! The flavors are incredible, and the staff is friendly and attentive.",
        img: "/Post3/Post.mp4", 
        accountName: "m_xxy5", 
        accountPic: "/Post3/Account.png",
        likesNum: 4588, 
        commentNum: 1835, 
        collectionNum: 812, 
        restaurantName: "OC & Lau Bar",
        reviewRank: 4.3, 
        reviewNum: 1480, 
        followingFlag: true, 
        feature: "Hot", 
        category: "hotpot", 
        closeTime: "7 PM", 
        distance: 3.8
    },

    { height: 215, imgFlag: true, 
        title: "A Sizzling Steak Experience",
        description: "I recently dined at a phenomenal steak restaurant and I must say, the experience was truly exceptional. The steaks were cooked to perfection, tender and juicy, and the service was top-notch with a friendly and attentive staff.",        
        img: "/Post4/Post.jpg", 
        accountName: "7ningun", 
        accountPic: "/Post4/Account.png",
        likesNum: 529, 
        commentNum: 135, 
        collectionNum: 18, 
        restaurantName: "Houston’s",
        reviewRank: 4.5, 
        reviewNum: 1686, 
        followingFlag: false, 
        feature: "Hot", 
        category: "American restaurant", 
        closeTime: "10 PM", 
        distance: 4.7
    },

    { height: 225, imgFlag: true, 
        title: "Brunch Bliss",
        description: "Delightful brunch spot that has become my go-to weekend destination. The menu offers a delectable array of breakfast and lunch options, from fluffy pancakes to savory omelettes, all served with a smile by the friendly staff.",    
        img: "/Post5/Post.jpg", 
        accountName: "alimusha.ms", 
        accountPic: "/Post5/Account.png",
        likesNum: 256, 
        commentNum: 15, 
        collectionNum: 2, 
        restaurantName: "Larsen",
        reviewRank: 3.8, 
        reviewNum: 132, 
        followingFlag: false, 
        feature: "Hot", 
        category: "American restaurant", 
        closeTime: "8 PM", 
        distance: 6.6
    },

    { height: 260, imgFlag: false, 
        title: "Best Korean restaurant you must try in LA",
        description: " Absolutely impressed. The mouthwatering selection of marinated meats, the interactive grilling experience, and the attentive service made it a memorable dining adventure I can't wait to repeat",        
        img: "/Post6/Post.mp4", 
        accountName: "looknamw", 
        accountPic: "/Post6/Account.png",
        likesNum: 129, 
        commentNum: 32, 
        collectionNum: 2, 
        restaurantName: "Sun Nong Dan",
        reviewRank: 4.3, 
        reviewNum: 1697, 
        followingFlag: false, 
        feature: "Hot", 
        category: "Korean restaurant", 
        closeTime: "6 PM", 
        distance: 3.2
    },

    { height: 205, imgFlag: true, 
        title: "A Classy Coffee Haven!",
        description: "I recently discovered a fancy coffee shop that is the epitome of elegance. From the luxurious ambiance to the meticulously crafted drinks, every sip was a delightful experience that made me feel like royalty.",        
        img: "/Post7/Post.jpg", 
        accountName: "pearwaprwa", 
        accountPic: "/Post7/Account.png",
        likesNum: 3, 
        commentNum: 0, 
        collectionNum: 0, 
        restaurantName: "Coffee Dose",
        reviewRank: 4.9, 
        reviewNum: 3376, 
        followingFlag: false, 
        feature: "Hot", 
        category: "Coffee Shop", 
        closeTime: "7 PM", 
        distance: 9.4
    },

    { height: 268, imgFlag: true, 
        title: "Taste of Vietnam in Every Bite",
        description: "I had the pleasure of dining at a Vietnam restaurant that took my taste buds on a flavorful journey. The authentic dishes, bursting with fragrant herbs and spices, combined with the warm and welcoming atmosphere, made it an unforgettable culinary experience.",        
        img: "/Post8/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post8/Account.png",
        likesNum: 5229, 
        commentNum: 1526, 
        collectionNum: 1182, 
        restaurantName: "Nép cafe & brunch",
        reviewRank: 4.5, 
        reviewNum: 496, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Cafe", 
        closeTime: "6 PM", 
        distance: 11.2
    },

    { height: 285, imgFlag: true, 
        title: "Yuk Dae Jang: A Spicy Haven for Korean Beef Soup",
        description: "Yuk Dae Jang is a haven for lovers of spicy and hearty Korean beef soup, offering a delectable and satisfying dining experience. Their flavorful broth, tender beef slices, and robust spices come together to create a bowl of comfort and warmth that will keep you coming back for more.",        
        img: "/Post10/Post.jpg", 
        accountName: "sally032598", 
        accountPic: "/Post10/Account.png",
        likesNum: 3527, 
        commentNum: 1133, 
        collectionNum: 834, 
        restaurantName: "Yuk Dae Jang",
        reviewRank: 4.2, 
        reviewNum: 136, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Korean restaurant", 
        closeTime: "9 PM", 
        distance: 7.8
    },

    { height: 225, imgFlag: true, 
        title: "Cozy Retreat for Coffee Aficionados",
        description: "Nook Coffee Bar provides a cozy and inviting atmosphere for coffee lovers, serving up expertly crafted beverages with a focus on quality and taste. From their rich and aromatic espresso to their specialty brews, Nook Coffee Bar is a delightful destination to relax, savor a cup of coffee, and escape the hustle and bustle of the outside world.",        
        img: "/Post9/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post9/Account.png",
        likesNum: 3196, 
        commentNum: 968, 
        collectionNum: 350, 
        restaurantName: "Nook Coffee Bar",
        reviewRank: 4.7, 
        reviewNum: 163, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Coffee Shop",
        closeTime: "9 PM", 
        distance: 6.3
    },

    { height: 215, imgFlag: true, 
        title: "Rustic Hideaway for Culinary Delights",
        description: "Oak & Coa offers a charming and rustic dining experience, combining a cozy ambiance with a menu full of delightful culinary creations. From their thoughtfully prepared dishes to their carefully curated wine selection, Oak & Coa provides a memorable dining experience that showcases the beauty of simple yet exceptional flavors.",         
        img: "/Post11/Post.jpg", 
        accountName: "sabrinawu_21", 
        accountPic: "/Post11/Account.png",
        likesNum: 1867, 
        commentNum: 913, 
        collectionNum: 202, 
        restaurantName: "Oak & Coal",
        reviewRank: 4.6, 
        reviewNum: 238, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Japanese restaurant", 
        closeTime: "8 PM", 
        distance: 9.2
    },

    { height: 223, imgFlag: true, 
        title: "Taste of Thailand's Vibrant Street Cuisine",
        description: "Thai Street Food brings the vibrant flavors of Thailand's street food scene to life with their authentic and flavorful dishes. From the aromatic curries to the tangy and spicy stir-fries, Siam Station delivers a taste of Thailand that will transport your taste buds to the bustling streets of Bangkok.",        
        img: "/Post12/Post.jpg", 
        accountName: "cocochou_", 
        accountPic: "/Post12/Account.png",
        likesNum: 3367, 
        commentNum: 1623, 
        collectionNum: 955, 
        restaurantName: "Siam Station Thai",
        reviewRank: 4.3, 
        reviewNum: 128, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Thai restaurant", 
        closeTime: "9 PM", 
        distance: 10.1
    },

    { height: 223, imgFlag: true, 
        title: "Nourishing Bowls of Vietnamese Delight",
        description: " Súp Noodle Bar delivers a delightful experience with their flavorful and comforting Vietnamese noodle bowls. From the aromatic broth to the perfectly cooked noodles and fresh toppings, each bowl at Súp Noodle Bar is a satisfying and nourishing delight for the senses.",        
        img: "/Post14/Post.jpg", 
        accountName: "shiuanfoodie", 
        accountPic: "/Post14/Account.png",
        likesNum: 567, 
        commentNum: 223, 
        collectionNum: 16, 
        restaurantName: "Súp Noodle Bar",
        reviewRank: 4.5, 
        reviewNum: 704, 
        followingFlag: false, 
        feature: "Hot", 
        category: "Asian Fusion", 
        closeTime: "8 PM", 
        distance: 6.3
    },

    { height: 265, imgFlag: false, 
        title: "Korean Culinary Journey",
        description: "Sookdal takes you on a flavorful journey through Korean cuisine, serving up authentic and mouthwatering dishes that capture the essence of Korean flavors. From the savory grilled meats to the spicy and comforting stews, Sookdal offers a memorable dining experience that will leave you craving for more.",        
        img: "/Post13/Post.mp4", 
        accountName: "shiuanfoodie", 
        accountPic: "/Post13/Account.png",
        likesNum: 662, 
        commentNum: 53, 
        collectionNum: 21, 
        restaurantName: "Sookdal",
        reviewRank: 4.4, 
        reviewNum: 269, 
        followingFlag: false, 
        feature: "Hot", 
        category: "Korean barbecue restaurant", 
        closeTime: "10 PM", 
        distance: 3.3
    },

    { height: 216, imgFlag: true, 
        title:"Bubble Tea Haven with Tasty Treats",
        description: "Omomo is a haven for bubble tea lovers, offering a wide variety of delicious flavors and customizable options that will satisfy any craving. With their refreshing drinks and delectable snacks, Omomo is the perfect place to indulge in a delightful and satisfying treat.",        
        img: "/Post15/Post.jpg", 
        accountName: "whoruins", 
        accountPic: "/Post15/Account.png",
        likesNum: 167, 
        commentNum: 23, 
        collectionNum: 32, 
        restaurantName: "Omomo",
        reviewRank: 4.4, 
        reviewNum: 548, 
        followingFlag: false, 
        feature: "Hot", 
        category: "Boba tea store", 
        closeTime: "6 PM", 
        distance: 8.2
    },

    { height: 251, imgFlag: true, 
        title: "Unforgettable Dumpling Delights",
        description: "Din Tai Fung never disappoints with its delectable dumplings that are expertly crafted with precision and filled with flavorful ingredients. From the delicate skins to the mouthwatering fillings, every bite at Din Tai Fung is a testament to their commitment to culinary excellence.",        
        img: "/Post16/Post.jpg", 
        accountName: "jeremyzz2", 
        accountPic: "/Post16/Account.png",
        likesNum: 713, 
        commentNum: 323, 
        collectionNum: 115, 
        restaurantName: "Din Tai Fung",
        reviewRank: 4.5, 
        reviewNum: 3038, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Taiwanese restaurant", 
        closeTime: "8 PM", 
        distance: 2.8
    },

    { height: 208, imgFlag: true, 
        title: "Grilled Delight for the Taste Buds",
        description: "Gyutan Tsukasa USA offers a unique and tantalizing experience with their expertly grilled beef tongue dishes. The succulent and flavorful gyutan, paired with their delicious side dishes, make it a must-visit destination for meat lovers seeking a memorable culinary adventure.",        
        img: "/Post17/Post.jpg", 
        accountName: "jeremyzz2", 
        accountPic: "/Post17/Account.png",
        likesNum: 213, 
        commentNum: 113, 
        collectionNum: 23, 
        restaurantName: "Gyutan Tsukasa",
        reviewRank: 4.7, 
        reviewNum: 207, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Japanese restaurant", 
        closeTime: "6 PM", 
        distance: 8.3
    },

    { height: 237, imgFlag: true, 
        title: "Sparkling Culinary Experience",
        description: "Gem Dining truly shines with its impeccable service, exquisite flavors, and stunning presentation. Each dish is a gem in itself, leaving a lasting impression of a truly exceptional dining experience.",        
        img: "/Post18/Post.jpg", 
        accountName: "jeremyzz2", 
        accountPic: "/Post18/Account.png",
        likesNum: 317, 
        commentNum: 33, 
        collectionNum: 12, 
        restaurantName: "Gem Dining",
        reviewRank: 4.6, 
        reviewNum: 240, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Asian Fusion", 
        closeTime: "9 PM", 
        distance: 4.2
    },

    { height: 253, imgFlag: true, 
        title: "A Culinary Delight: Exploring Seasonal Delights at Solstice Seasonal Kitchen & Bar",
        description: "Solstice Seas,onal Kitchen & Bar exceeded my expectations! The food was exceptional, with fresh and flavorful dishes that showcased the best of seasonal ingredients. The service was attentive and the atmosphere was inviting. A top-notch dining experience that I highly recommend.",
        img: "/Post19/Post.jpg", 
        accountName: "_jeremy_jin", 
        accountPic: "/Post19/Account.png",
        likesNum: 587, 
        commentNum: 69, 
        collectionNum: 26, 
        restaurantName: "Solstice Seasonal",
        reviewRank: 4.6, 
        reviewNum: 240, 
        followingFlag: true, 
        feature: "Hot", 
        category: "Asian Fusion", 
        closeTime: "6 PM", 
        distance: 5.6
    },

    { height: 247, imgFlag: true, 
        title: "A Delightful Japanese Dining Experience at Izakaya Osen Irvine",
        description: "Izakaya Osen in Irvine provides a wonderful dining experience. The cozy ambiance, fresh sushi, flavorful ramen, and attentive staff make it a great choice. While prices are higher, the quality justifies it. Highly recommended for a delightful Japanese meal in Irvine.",         
        img: "/Post20/Post.jpg", 
        accountName: "william.wang", 
        accountPic: "/Post20/Account.png",
        likesNum: 127, 
        commentNum: 9, 
        collectionNum: 1,
        restaurantName: "Izakaya Osen Irvine",
        reviewRank: 4.7, 
        reviewNum: 139, 
        followingFlag: false, 
        feature: "Hot", 
        category: "Japanese restaurant", 
        closeTime: "7 PM", 
        distance: 9.8
    },

    // { height: 233,imgFlag:true, title: "Thai food is so good🤤", description: "Siam Station | Irvine, CA \nThai food is so good🤤here are the deats : \nPad Thai \n Pad See Ew \nChinese Broccoli", 
    //   img: "/Post1/Post.jpg", accountName: "clovchoi", accountPic: "/Post1/Account.png",
    //   likesNum: 520, commentNum: 5, collectionNum: 1, restaurantName:"Siam Station",
    //   reviewRank:4.3, reviewNum: 128, followingFlag: false, feature: "Hot", 
    //   category:"Thai", closeTime: "7 PM", distance: 8.8},

    // { height: 272, imgFlag:false, title: "Had to get some vids of my first time at iniristorante!", description: "It’s been on my list of places to try for months 🤤 been feeling inspired to create food content outside of the kitchen again so I thought I’d share! (Bringing back the Yelp elite in me hahaha)🫶🏼", 
    //   img: "/Post2/Post.mp4", accountName: "skatewithlin", accountPic: "/Post2/Account.png",
    //   likesNum: 165, commentNum: 32, collectionNum: 76, restaurantName:"Ini Ristorane",
    //   reviewRank:4.5, reviewNum: 231, followingFlag: true, feature: "Hot", 
    //   category:"Fusion", closeTime: "10 PM", distance: 7.1},

    // { height: 285, imgFlag:true, title: "I have va good review for you all today 🫶", description: "hello friends! \nI have va good review for you all today 🫶\nSo my family and I went to folksrestaurantand we knew this place was amazing, but it really blew our minds \n", 
    //   img: "/Post3/Post.jpg", accountName: "bishesdishes", accountPic: "/Post3/Account.png",
    //   likesNum: 326, commentNum: 5, collectionNum: 0, restaurantName:"Folks Pizzeria",
    //   reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot", 
    //   category:"Pizza", closeTime: "9 PM", distance: 10.8},

    // { height: 170, imgFlag:true, title: "Introducing Northern-style Vietnamese cuisine", description: "\nCLICK HERE TO FOLLOW\n supnoodlebar \n\nIf you would like to have your restaurant featured on our site for FREE, please email us at\naapiownedrestaurants gmail.com", 
    //   img: "/Post4/Post.jpg", accountName: "fkndelicious", accountPic: "/Post4/Account.png",
    //   likesNum: 772, commentNum: 29, collectionNum: 0, restaurantName:"SÚP NOODLE BAR",
    //   reviewRank:4.5, reviewNum: 704, followingFlag: false, feature: "Hot", 
    //   category:"Asian Fusion", closeTime: "10 PM", distance: 12.8},

    // { height: 275, imgFlag:false, title: "Anyone else obsessed with bone marrow? 😅", description: "anyone else obsessed with bone marrow? 😅\n\nft. nep.cafe\n\n", 
    //   img: "/Post5/Post.mp4", accountName: "takeoneroad", accountPic: "/Post5/account.png",
    //   likesNum: 1322, commentNum: 981, collectionNum: 2312, restaurantName:"Nép cafe & brunch",
    //   reviewRank:4.7, reviewNum: 80, followingFlag: true, feature: "Hot", 
    //   category:"Cafe", closeTime: "7 PM", distance: 3.4},

    // { height: 260, imgFlag:true, title: "everything we ate at anjin costamesa", description: "everything we ate at anjin_costamesa", 
    //   img: "/Post6/Post.jpg", accountName: "johnson.doa", accountPic: "/Post6/account.png",
    //   likesNum: 3965, commentNum: 966, collectionNum: 1255, restaurantName:"Anjin",
    //   reviewRank:4.6, reviewNum: 486, followingFlag: true, feature: "Hot", 
    //   category:" Japanese", closeTime: "10 PM", distance: 1.8},

    // { height: 218, imgFlag:true, title: "📌 Rising Phoenix Milk Tea $5.00 USD", description: "Best Oolong milk tea I’ve ever had! Their boba milk tea was truly exceptional, you could literally taste the quality of the tea compared to many other boba chains! The service was 10/10, they wanted me to have a taste of my drink first before leaving to make sure I got my desired amount of sweetness (1-5). 10/10 recommended;)", 
    //   img: "/Post7/Post.jpg", accountName: "foodie.914", accountPic: "/Post7/account.png",
    //   likesNum: 754, commentNum: 28, collectionNum: 76, restaurantName:"Orobae",
    //   reviewRank:4.6, reviewNum: 384, followingFlag: false, feature: "Hot", 
    //   category:"Boba tea store", closeTime: "8 PM", distance: 18.8},

    // { height: 280, imgFlag:true, title: "Very cute spot next to the beach", description: "At Larsen's Grill, the food is as spectacular as the scenery.", 
    //   img: "/Post8/Post.jpg", accountName: "Cindy_0314", accountPic: "/Post8/account.png",
    //   likesNum: 36597, commentNum: 3223, collectionNum: 2756, restaurantName:"Larsen",
    //   reviewRank:3.8, reviewNum: 132, followingFlag: true, feature: "Hot", 
    //   category:"American Restaurant", closeTime: "7 PM", distance: 19.1},

    // { height: 214, imgFlag:true, title: "I feel like a new boba shop opens in Irvine every week", description: "I feel like a new boba shop opens in Irvine every week and cloudycotea is another one of them :-) Located in Heritage Plaza near Orobae, across from Omomo, and a short walk from Irvine High, Cloudy Co has a variety of drinks AND desserts, separating it from other shops.", 
    // img: "/Post9/Post.jpg", accountName: "hungryhingco", accountPic: "/Post9/account.png",
    // likesNum: 102, commentNum: 12, collectionNum: 2, restaurantName:"Cloudy Co", 
    // reviewRank:4.2, reviewNum: 84, followingFlag: false, feature: "Hot", 
    // category:"Bubble Tea Store", closeTime: "8 PM", distance: 16.7},

    // { height: 282, imgFlag:false, title: "Have you ever seen a pink shipping container serving coffee? ☕️", description: "🔷This pretty pink container serves specialty coffees in addition to cheeky merchandise and vegan/keto-friendly treats made with natural ingredients. It’s dog friendly and offers “puppy cracks” for your dogs. Overall, It’s on the pricier side (it’s in Irvine after all 😀), but it’s a fun and unique experience. Tip: You can find it between two buildings.", 
    // img: "/Post10/Post.mp4", accountName: "jazwonder", accountPic: "/Post10/account.png",
    // likesNum: 555, commentNum: 312, collectionNum: 4376, restaurantName:"Dose In The Box", 
    // reviewRank:4.4, reviewNum: 84, followingFlag: false, feature: "Hot", 
    // category:"Coffee Shop", closeTime: "6 PM", distance: 5.1},

    // { height: 298, imgFlag:true, title: "midday matcha break 🫶🏼✨", description: "midday matcha break 🫶🏼✨", 
    // img: "/Post11/Post.jpg", accountName: "lifeandlyss", accountPic: "/Post11/account.png",
    // likesNum: 178, commentNum: 32, collectionNum: 76, restaurantName:"Nook coffee Bar", 
    // reviewRank:4.7, reviewNum: 163, followingFlag: false, feature: "Hot", 
    // category:"Coffee shop", closeTime: "7 PM", distance: 5.8},

    // { height: 260, imgFlag:true, title: "Night before X-mas~~~ North Italian, amazing food. ", description: "Night before X-mas~~~ North Italian, amazing food. ", 
    // img: "/Post12/Post.jpg", accountName: "m_xxy5", accountPic: "/Post12/account.png",
    // likesNum: 3235, commentNum: 712, collectionNum: 1716, restaurantName:"North Italian", 
    // reviewRank:4.5, reviewNum: 2892, followingFlag: true, feature: "Hot", 
    // category:"Italian", closeTime: "11 PM", distance: 17.6},

    // { height: 280, imgFlag:true, title: "Brunch date with my soon to be bride Monica~", description: "📍Irvine, CA\n angelinaspizzeria \n\nSquid ink pasta is a must !!!!!!!", 
    // img: "/Post13/Post.jpg", accountName: "chapterrita", accountPic: "/Post13/account.png",
    // likesNum: 296, commentNum: 132, collectionNum: 176, restaurantName:"Angelina's Pizzeria", 
    // reviewRank:4.5, reviewNum: 706, followingFlag: true, feature: "Hot", 
    // category:"Pizza", closeTime: "9 PM", distance: 6.8},

    // { height: 283, imgFlag:false, title: "Join me for some Japanese BBQ at manpuku🥩!", description: "What I ordered: - Uni beef sashimi  - Manpuku salad - Fresh corn - Angus Beef tongue",
    // img: "/Post14/Post.mp4", accountName: "jill.akemi", accountPic: "/Post14/account.png",
    // likesNum: 297, commentNum: 28, collectionNum: 0, restaurantName:"Manpuku Jp BBQ",
    // reviewRank:4.4, reviewNum: 204, followingFlag: false, feature: "Hot", 
    // category:"Yakiniku", closeTime: "5 PM", distance: 2.3},

//   ],
//   "Following":[

    { height: 233, imgFlag: false, 
        title: "A Delightful Thai Adventure!",
        description: "The Thai restaurant in town is absolutely amazing! The flavors are incredible, and the staff is friendly and attentive.",    
        img: "/Post3/Post.mp4", 
        accountName: "m_xxy5", 
        accountPic: "/Post3/Account.png",
        likesNum: 4588, 
        commentNum: 1835, 
        collectionNum: 812, 
        restaurantName: "OC & Lau Bar",
        reviewRank: 4.3, 
        reviewNum: 1480, 
        followingFlag: true, 
        feature: "Following", 
        category: "hotpot", 
        closeTime: "7 PM", 
        distance: 3.8
    },

    { height: 268, imgFlag: true, 
        title: "Charming Brunch Spot for a Relaxing Morning",
        description: "Nép Cafe & Brunch is a charming and cozy establishment that offers a delightful brunch experience. With their delectable menu options, friendly service, and inviting ambiance, Nép Cafe & Brunch is the perfect place to enjoy a leisurely morning meal in a welcoming setting.",     
        img: "/Post8/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post8/Account.png",
        likesNum: 5229, 
        commentNum: 2526, 
        collectionNum: 1182, 
        restaurantName: "Nép cafe & brunch",
        reviewRank: 4.5, 
        reviewNum: 496, 
        followingFlag: true, 
        feature: "Following", 
        category: "Cafe", 
        closeTime: "6 PM", 
        distance: 11.2
    },

    { height: 285, imgFlag: true, 
        title: "Yuk Dae Jang: A Spicy Haven for Korean Beef Soup",
        description: "Yuk Dae Jang is a haven for lovers of spicy and hearty Korean beef soup, offering a delectable and satisfying dining experience. Their flavorful broth, tender beef slices, and robust spices come together to create a bowl of comfort and warmth that will keep you coming back for more.",        
        img: "/Post10/Post.jpg", 
        accountName: "sally032598", 
        accountPic: "/Post10/Account.png",
        likesNum: 3527, 
        commentNum: 1133, 
        collectionNum: 834, 
        restaurantName: "Yuk Dae Jang",
        reviewRank: 4.2, 
        reviewNum: 136, 
        followingFlag: true, 
        feature: "Following", 
        category: "Korean restaurant", 
        closeTime: "9 PM", 
        distance: 7.8
    },

    { height: 225, imgFlag: true, 
        title: "Cozy Retreat for Coffee Aficionados",
        description: "Nook Coffee Bar provides a cozy and inviting atmosphere for coffee lovers, serving up expertly crafted beverages with a focus on quality and taste. From their rich and aromatic espresso to their specialty brews, Nook Coffee Bar is a delightful destination to relax, savor a cup of coffee, and escape the hustle and bustle of the outside world.",    
        img: "/Post9/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post9/Account.png",
        likesNum: 3196, 
        commentNum: 968, 
        collectionNum: 350, 
        restaurantName: "Nook Coffee Bar",
        reviewRank: 4.7, 
        reviewNum: 163, 
        followingFlag: true, 
        feature: "Following", 
        category: "Coffee Shop",
        closeTime: "9 PM", 
        distance: 6.3
    },

    { height: 215, imgFlag: true, 
        title: "Rustic Hideaway for Culinary Delights",
        description: "Oak & Coa offers a charming and rustic dining experience, combining a cozy ambiance with a menu full of delightful culinary creations. From their thoughtfully prepared dishes to their carefully curated wine selection, Oak & Coa provides a memorable dining experience that showcases the beauty of simple yet exceptional flavors.",         
        img: "/Post11/Post.jpg", 
        accountName: "sabrinawu_21", 
        accountPic: "/Post11/Account.png",
        likesNum: 1867, 
        commentNum: 913, 
        collectionNum: 202, 
        restaurantName: "Oak & Coal",
        reviewRank: 4.6, 
        reviewNum: 238, 
        followingFlag: true, 
        feature: "Following", 
        category: "Japanese restaurant", 
        closeTime: "8 PM", 
        distance: 9.2
    },

    { height: 223, imgFlag: true, 
        title: "Taste of Thailand's Vibrant Street Cuisine",
        description: "Thai Street Food brings the vibrant flavors of Thailand's street food scene to life with their authentic and flavorful dishes. From the aromatic curries to the tangy and spicy stir-fries, Siam Station delivers a taste of Thailand that will transport your taste buds to the bustling streets of Bangkok.",        
        img: "/Post12/Post.jpg", 
        accountName: "cocochou_", 
        accountPic: "/Post12/Account.png",
        likesNum: 3367, 
        commentNum: 1623, 
        collectionNum: 955, 
        restaurantName: "Siam Station Thai",
        reviewRank: 4.3, 
        reviewNum: 128, 
        followingFlag: true, 
        feature: "Following", 
        category: "Thai restaurant", 
        closeTime: "9 PM", 
        distance: 10.1
    },

    { height: 251, imgFlag: true, 
        title: "Unforgettable Dumpling Delights",
        description: "Din Tai Fung never disappoints with its delectable dumplings that are expertly crafted with precision and filled with flavorful ingredients. From the delicate skins to the mouthwatering fillings, every bite at Din Tai Fung is a testament to their commitment to culinary excellence.",        
        img: "/Post16/Post.jpg", 
        accountName: "jeremyzz2", 
        accountPic: "/Post16/Account.png",
        likesNum: 713, 
        commentNum: 323, 
        collectionNum: 115, 
        restaurantName: "Din Tai Fung",
        reviewRank: 4.5, 
        reviewNum: 3038, 
        followingFlag: true, 
        feature: "Following", 
        category: "Taiwanese restaurant", 
        closeTime: "8 PM", 
        distance: 2.8
    },

    { height: 208, imgFlag: true, 
        title: "Grilled Delight for the Taste Buds",
        description: "Gyutan Tsukasa USA offers a unique and tantalizing experience with their expertly grilled beef tongue dishes. The succulent and flavorful gyutan, paired with their delicious side dishes, make it a must-visit destination for meat lovers seeking a memorable culinary adventure.",        
        img: "/Post17/Post.jpg", 
        accountName: "jeremyzz2", 
        accountPic: "/Post17/Account.png",
        likesNum: 213, 
        commentNum: 113, 
        collectionNum: 23, 
        restaurantName: "Gyutan Tsukasa",
        reviewRank: 4.7, 
        reviewNum: 207, 
        followingFlag: true, 
        feature: "Following", 
        category: "Japanese restaurant", 
        closeTime: "6 PM", 
        distance: 8.3
    },

    { height: 237, imgFlag: true, 
        title: "Sparkling Culinary Experience",
        description: "Gem Dining truly shines with its impeccable service, exquisite flavors, and stunning presentation. Each dish is a gem in itself, leaving a lasting impression of a truly exceptional dining experience.",
        img: "/Post18/Post.jpg", 
        accountName: "jeremyzz2", 
        accountPic: "/Post18/Account.png",
        likesNum: 317, 
        commentNum: 33, 
        collectionNum: 12, 
        restaurantName: "Gem Dining",
        reviewRank: 4.6, 
        reviewNum: 240, 
        followingFlag: true, 
        feature: "Following", 
        category: "Asian Fusion", 
        closeTime: "9 PM", 
        distance: 4.2
    },

    { height: 253, imgFlag: true, 
        title: "A Culinary Delight: Exploring Seasonal Delights at Solstice Seasonal Kitchen & Bar",
        description: "Solstice Seas,onal Kitchen & Bar exceeded my expectations! The food was exceptional, with fresh and flavorful dishes that showcased the best of seasonal ingredients. The service was attentive and the atmosphere was inviting. A top-notch dining experience that I highly recommend.",
        img: "/Post19/Post.jpg", 
        accountName: "_jeremy_jin", 
        accountPic: "/Post19/Account.png",
        likesNum: 587, 
        commentNum: 69, 
        collectionNum: 26, 
        restaurantName: "Solstice Seasonal",
        reviewRank: 4.6, 
        reviewNum: 240, 
        followingFlag: true, 
        feature: "Following", 
        category: "Asian Fusion", 
        closeTime: "6 PM", 
        distance: 5.6
    },

    // { height: 233, imgFlag:true, title: "Enjoyed a delicious ramen dinner at HiroNori Craft Ramen at the Enclave", description: "Enjoyed a delicious ramen dinner at HiroNori Craft Ramen at the Enclave. Pictured here is the Spicy Dipping Cold Noodles, the Tonkatsu Ramen, the Spicy Tuna on Crispy Rice and the Pork Belly Buns. hironoriramen", 
    // img: "/Post15/Post.jpg", accountName: "shortsweet2", accountPic: "/Post15/account.png",
    // likesNum: 2199, commentNum: 32, collectionNum: 76, restaurantName:"Hironori",
    // reviewRank:4.6, reviewNum: 1921, followingFlag: false, feature: "Following", 
    // category:"Ramen ", closeTime: "11 PM", distance: 6.9},

    // { height: 282, imgFlag:true, title: "Love my drinks super sweet but this place is not as sweet as most boba places even at 100%", description: "✧ mango high mountain tea ($5.30) - all of their fruit teas are made with high mountain oolong tea. this one was the most fragrant so it was def my favorite out of the two✧ passionfruit high mountain tea ($5.30) - this one wasn't bad but i felt like it wasn't as fragrant as mango", 
    // img: "/Post16/Post.jpg", accountName: "friesandchi", accountPic: "/Post16/account.png",
    // likesNum: 365, commentNum: 132, collectionNum: 76, restaurantName:"Soma tea & mocktail",
    // reviewRank:4.5, reviewNum: 57, followingFlag: true, feature: "Following", 
    // category:"Bubble tea store", closeTime: "8 PM", distance: 5.2},

    //   ],

//   "New":[
    // New Reviews

    { height: 268, imgFlag: true, 
        title: "Charming Brunch Spot for a Relaxing Morning",
        description: "Nép Cafe & Brunch is a charming and cozy establishment that offers a delightful brunch experience. With their delectable menu options, friendly service, and inviting ambiance, Nép Cafe & Brunch is the perfect place to enjoy a leisurely morning meal in a welcoming setting.",     
        img: "/Post8/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post8/Account.png",
        likesNum: 5229, 
        commentNum: 2526, 
        collectionNum: 1182, 
        restaurantName: "Nép cafe & brunch",
        reviewRank: 4.5, 
        reviewNum: 496, 
        followingFlag: true, 
        feature: "New", 
        category: "Cafe", 
        closeTime: "6 PM", 
        distance: 11.2
    },

    { height: 215, imgFlag: true, 
        title: "Rustic Hideaway for Culinary Delights",
        description: "Oak & Coa offers a charming and rustic dining experience, combining a cozy ambiance with a menu full of delightful culinary creations. From their thoughtfully prepared dishes to their carefully curated wine selection, Oak & Coa provides a memorable dining experience that showcases the beauty of simple yet exceptional flavors.",         
        img: "/Post11/Post.jpg", 
        accountName: "sabrinawu_21", 
        accountPic: "/Post11/Account.png",
        likesNum: 1867, 
        commentNum: 913, 
        collectionNum: 202, 
        restaurantName: "Oak & Coal",
        reviewRank: 4.6, 
        reviewNum: 238, 
        followingFlag: true, 
        feature: "New", 
        category: "Japanese restaurant", 
        closeTime: "8 PM", 
        distance: 9.2
    },

    { height: 223, imgFlag: true, 
        title: "Taste of Thailand's Vibrant Street Cuisine",
        description: "Thai Street Food brings the vibrant flavors of Thailand's street food scene to life with their authentic and flavorful dishes. From the aromatic curries to the tangy and spicy stir-fries, Siam Station delivers a taste of Thailand that will transport your taste buds to the bustling streets of Bangkok.",        
        img: "/Post12/Post.jpg", 
        accountName: "cocochou_", 
        accountPic: "/Post12/Account.png",
        likesNum: 3367, 
        commentNum: 1623, 
        collectionNum: 955, 
        restaurantName: "Siam Station Thai",
        reviewRank: 4.3, 
        reviewNum: 128, 
        followingFlag: true, 
        feature: "New", 
        category: "Thai restaurant", 
        closeTime: "9 PM", 
        distance: 10.1
    },

    { height: 216, imgFlag: true, 
        title:"Bubble Tea Haven with Tasty Treats",
        description: "Omomo is a haven for bubble tea lovers, offering a wide variety of delicious flavors and customizable options that will satisfy any craving. With their refreshing drinks and delectable snacks, Omomo is the perfect place to indulge in a delightful and satisfying treat.",        
        img: "/Post15/Post.jpg", 
        accountName: "whoruins", 
        accountPic: "/Post15/Account.png",
        likesNum: 167, 
        commentNum: 23, 
        collectionNum: 32, 
        restaurantName: "Omomo",
        reviewRank: 4.4, 
        reviewNum: 548, 
        followingFlag: false, 
        feature: "New", 
        category: "Boba tea store", 
        closeTime: "6 PM", 
        distance: 8.2
    },

    // { height: 290, imgFlag:true, title: "Honey Pig Irvine", description: "Honey Pig Irvine⭐️⭐️⭐️", 
    // img: "/Post17/Post.jpg", accountName: "irvinefoodies", accountPic: "/Post17/account.png",
    // likesNum: 629, commentNum: 74, collectionNum: 6, restaurantName:"HoneyPig",
    // reviewRank:4.2, reviewNum: 359, followingFlag: false, feature: "New", 
    // category:"Korean BBQ", closeTime: "9 PM", distance: 9.7},

    // { height: 210, imgFlag:true, title: "Snooze A.M. Eatery📍(chain)", description: "🥚Huevos tostada ⭐️7/10 $12.25\n🥑Smashed avocado⭐️6/10 $14.95\ 🍫Hot chocolate ⭐️8/10 $4.50\n\n\nThe ambiance is very scenic. The food could use more flavor especially for the price. If i were to choose, I would go first to watch over this place for brunch.", 
    // img: "/Post18/Post.jpg", accountName: "phaties.eat", accountPic: "/Post18/account.png",
    // likesNum: 1139, commentNum: 32, collectionNum: 76, restaurantName:"Snooze, AN A.M.",
    // reviewRank:4.4, reviewNum: 1915, followingFlag: false, feature: "New", 
    // category:"Breakfast", closeTime: "5 PM", distance: 3.9},

    // { height: 310, imgFlag:false, title: "Houstonsrestaurants| always a solid option", description: "Always a solid option, how do we always forget about the hawaiian rib eye! and the five nut brownie is my new fav dessert🍫🤤", 
    // img: "/Post19/Post.mp4", accountName: "conniechews", accountPic: "/Post19/account.png",
    // likesNum: 719, commentNum: 51, collectionNum: 117, restaurantName:"Houston’s Restaurant ",
    // reviewRank:4.5, reviewNum: 1682, followingFlag: false, feature: "New", 
    // category:"American", closeTime: "9 PM", distance: 6.5},

    // { height: 221, imgFlag:true, title: "Geat for any occasion and private events", description: "We love going to eddievs_ it’s great for any occasion and private events too.. especially when there’s cheesy potatoes involved 😉They have locations in Michigan, Massachusetts and more! Check them out!", 
    // img: "/Post20/Post.jpg", accountName: "bossblue.eats", accountPic: "/Post20/account.png",
    // likesNum: 269, commentNum: 14, collectionNum: 36, restaurantName:"Eddie V’s Seafood",
    // reviewRank:4.7, reviewNum: 743, followingFlag: false, feature: "New", 
    // category:"Seafood", closeTime: "9 PM", distance: 17.6},

    //   ],
//   "Best":[
    // { height: 263, imgFlag:true, title: "Beautiful Saturday meal 🪴", description: "", 
    // img: "/Post21/Post.jpg", accountName: "Cindy_0314", accountPic: "/Post21/account.png",
    // likesNum: 8110, commentNum: 232, collectionNum: 3676, restaurantName:"Roger's Gardens",
    // reviewRank:4.6, reviewNum: 1434, followingFlag: false, feature: "Best", 
    // category:"American", closeTime: "10 PM", distance: 5.8},

// Best Reviews
    { height: 233, imgFlag: false, 
        title: "A Delightful Thai Adventure",
        description: "The Thai restaurant in town is absolutely amazing! The flavors are incredible, and the staff is friendly and attentive.",
        img: "/Post3/Post.mp4", 
        accountName: "m_xxy5", 
        accountPic: "/Post3/Account.png",
        likesNum: 4588, 
        commentNum: 1835, 
        collectionNum: 812, 
        restaurantName: "OC & Lau Bar",
        reviewRank: 4.3, 
        reviewNum: 1480, 
        followingFlag: true, 
        feature: "Best", 
        category: "hotpot", 
        closeTime: "7 PM", 
        distance: 3.8
    },

    { height: 268, imgFlag: true, 
        title: "Charming Brunch Spot for a Relaxing Morning",
        description: "Nép Cafe & Brunch is a charming and cozy establishment that offers a delightful brunch experience. With their delectable menu options, friendly service, and inviting ambiance, Nép Cafe & Brunch is the perfect place to enjoy a leisurely morning meal in a welcoming setting.",         
        img: "/Post8/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post8/Account.png",
        likesNum: 5229, 
        commentNum: 2526, 
        collectionNum: 1182, 
        restaurantName: "Nép cafe & brunch",
        reviewRank: 4.5, 
        reviewNum: 496, 
        followingFlag: true, 
        feature: "Best", 
        category: "Cafe", 
        closeTime: "6 PM", 
        distance: 11.2
    },

    { height: 225, imgFlag: true, 
        title: "Cozy Retreat for Coffee Aficionados",
        description: "Nook Coffee Bar provides a cozy and inviting atmosphere for coffee lovers, serving up expertly crafted beverages with a focus on quality and taste. From their rich and aromatic espresso to their specialty brews, Nook Coffee Bar is a delightful destination to relax, savor a cup of coffee, and escape the hustle and bustle of the outside world.",        
        img: "/Post9/Post.jpg", 
        accountName: "hsin_0314", 
        accountPic: "/Post9/Account.png",
        likesNum: 3196, 
        commentNum: 968, 
        collectionNum: 350, 
        restaurantName: "Nook Coffee Bar",
        reviewRank: 4.7, 
        reviewNum: 163, 
        followingFlag: true, 
        feature: "Best", 
        category: "Coffee Shop",
        closeTime: "9 PM", 
        distance: 6.3
    },

    { height: 223, imgFlag: true, 
        title: "Taste of Thailand's Vibrant Street Cuisine",
        description: "Thai Street Food brings the vibrant flavors of Thailand's street food scene to life with their authentic and flavorful dishes. From the aromatic curries to the tangy and spicy stir-fries, Siam Station delivers a taste of Thailand that will transport your taste buds to the bustling streets of Bangkok.",        
        img: "/Post12/Post.jpg", 
        accountName: "cocochou_", 
        accountPic: "/Post12/Account.png",
        likesNum: 3367, 
        commentNum: 1623, 
        collectionNum: 955, 
        restaurantName: "Siam Station Thai",
        reviewRank: 4.3, 
        reviewNum: 128, 
        followingFlag: true, 
        feature: "Best", 
        category: "Thai restaurant", 
        closeTime: "9 PM", 
        distance: 10.1
    },
    ],
};

export default data;
